name: pozadkey_v2
description: Pozadkey - Web & Mobile Engineer

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Third-party packages
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for better coding practices
  flutter_lints: ^2.0.0

flutter:
  # Ensure Material Icons font is included
  uses-material-design: true

  # Define custom fonts and their styles
  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/clash_display/ClashDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/clash_display/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/clash_display/ClashDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/clash_display/ClashDisplay-Semibold.ttf
          weight: 600
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Semibold.ttf
          weight: 600
